### ISSUE TITLE
compile failed

### ISSUE THREAD

**Issue by michaelqxd** [Predelnik/any_with_traits#1]
[ 14%] Building CXX object test/CMakeFiles/any_with_traits_test.dir/gtest-all.cc.o
[ 28%] Building CXX object test/CMakeFiles/any_with_traits_test.dir/test.cpp.o
/home/xmly/thirdparty/any_with_traits/test/test.cpp: In member function ?.irtual void any_all_Test::TestBody()?.
/home/xmly/thirdparty/any_with_traits/test/test.cpp:157:13: error: converting to ?.td::__cxx11::basic_stringstream<char>?.from initializer list would use explicit constructor ?.td::__cxx11::basic_stringstream<_CharT, _Traits, _Alloc>::basic_stringstream(const __string_type&, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_stringstream<_CharT, _Traits, _Alloc>::__string_type = std::__cxx11::basic_string<char>; std::ios_base::openmode = std::_Ios_Openmode]?
     ss = {""};
             ^
In file included from /home/xmly/thirdparty/any_with_traits/test/test.cpp:2:0:
/home/xmly/thirdparty/any_with_traits/test/../src/any_with_traits.h: In instantiation of ?.wt::detail::any_t<Traits>::any_t(awt::detail::any_t<Traits>::self&&) [with Traits = {any_trait::destructible}; awt::detail::any_t<Traits>::self = awt::detail::any_t<any_trait::destructible>]?.
/home/xmly/thirdparty/any_with_traits/test/test.cpp:131:21:   required from here
/home/xmly/thirdparty/any_with_traits/test/../src/any_with_traits.h:689:5: error: static assertion failed: class move construction is prohibited due to lack of movable trait
     static_assert(
     ^~~~~~~~~~~~~
/home/xmly/thirdparty/any_with_traits/test/../src/any_with_traits.h:692:11: error: ?.lass awt::detail::any_t<any_trait::destructible>?.has no member named ?.ove_from?
     this->move_from(std::move(other));
     ~~~~~~^~~~~~~~~
/home/xmly/thirdparty/any_with_traits/test/../src/any_with_traits.h: In instantiation of ?.wt::detail::any_t<Traits>::any_t(awt::detail::any_t<Traits>::self&&) [with Traits = {any_trait::destructible, any_trait::ostreamable}; awt::detail::any_t<Traits>::self = awt::detail::any_t<any_trait::destructible, any_trait::ostreamable>]?.
/home/xmly/thirdparty/any_with_traits/test/test.cpp:152:42:   required from here
/home/xmly/thirdparty/any_with_traits/test/../src/any_with_traits.h:689:5: error: static assertion failed: class move construction is prohibited due to lack of movable trait
     static_assert(
     ^~~~~~~~~~~~~
/home/xmly/thirdparty/any_with_traits/test/../src/any_with_traits.h:692:11: error: ?.lass awt::detail::any_t<any_trait::destructible, any_trait::ostreamable>?.has no member named ?.ove_from?
     this->move_from(std::move(other));

**Comment by Predelnik** [comment]
Thanks! 
It seems like one can't use construct `type x = something_convertible_to_type` if `type` is unmovable/uncopiable until C++17 so funnily enough it will compile with gcc7/clang4.0 with `c++1z`, I've just changed it to `type x (something_convertible_to_type)`. Also one minor problem with `stringstream`. I fixed tests and hopefully will setup travis or something to prevent such things in the future.

I'm a bit curious how you got interested in this experimental implementation? Sadly enough I haven't got to use it in any actual code for now.
